apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless
  namespace: paperless
  labels:
    app: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi