apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi